version: '2'
services:
  web:
    image: whyour/qinglong:2.17.2
    volumes:
      - ./data:/ql/data
    ports:
      - "0.0.0.0:5700:5700"
    environment:
      QlBaseUrl: '/'
    restart: unless-stopped
