version : '3'
networks:
  imaotai:
    driver: bridge
services:
  mysql:
    image: dockerproxy.com/mysql/mysql-server:8.0.32
    restart: always
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: 123456789
      MYSQL_DATABASE: 'campus_imaotai'
      MYSQL_ROOT_HOST: "%"
    ports:
      - 3307:3306
    volumes:
      - ./mysql/data:/var/lib/mysql/
      - ./mysql/config:/etc/mysql/my.cnf
      - ./mysql/logs:/logs
    command: [
          'mysqld',
          '--innodb-buffer-pool-size=80M',
          '--character-set-server=utf8mb4',
          '--collation-server=utf8mb4_unicode_ci',
          '--default-time-zone=+8:00',
          '--lower-case-table-names=1',
          '--default-authentication-plugin=mysql_native_password'
        ]
    privileged: true
    networks:
      - imaotai
  redis:
    image: redis:6.2.14
    restart: always
    container_name: redis
    volumes:
      - ./redis/data:/data
      - ./redis/conf/redis.conf:/usr/local/etc/redis/redis.conf
    command: "redis-server /usr/local/etc/redis/redis.conf"
    privileged: true
    networks:
      - imaotai
  nginx:
    image: imaotai/campus-admin-web:1.0.13
    restart: always
    container_name: nginx
    environment:
      # 时区上海
      TZ: Asia/Shanghai
    ports:
      - 7090:80
    volumes:
      - ./vue_campus_admin/nginx/conf/nginx.conf:/etc/nginx/nginx.conf
    privileged: true
    links:
      - campus-server:campus-server
    networks:
      - imaotai
  campus-server:
    image: imaotai/campus-modular:1.0.13
    restart: always
    container_name: campus-imaotai
    environment:
      # 时区上海
      TZ: Asia/Shanghai
      SERVER_PORT: 8160
      spring.config.additional-location: /home/campus/conf/application-prod.yml
    volumes:
      - ./campus-modular/conf:/home/campus/conf
    links:
      - mysql:mysql
      - redis:redis
    privileged: true
    networks:
      - imaotai
